### PR TITLE
Clean up modules

### PR DESCRIPTION
**Pull request by 89z**
- Update Go version
- Use correct import path for `cbind`
- Update version on some modules

### CODE REVIEW

**Comment by noborus** [comment]
Thank you very much.
There is a serious problem with tcell v2.2.0.
https://github.com/gdamore/tcell/issues/432
I will not update until it is fixed.

**Comment by 89z** [comment]
I reverted the change for tcell, kept other changes

**Comment by noborus** [comment]
Thank you. I will update it.

**Comment by 89z** [comment]
An alternative to Tcell is now available:

https://pkg.go.dev/github.com/walles/moar/twin

**Pull request merged**
