### PR TITLE
fix #48 add api WriteOriginalTillQuit. This is a variation of WriteOriginal()…

### LINKED ISSUE #48: Exit without clear screen
Currently the screen is always cleared on exit:

https://github.com/noborus/ov/blob/c1ca769f8805e842688c89328084be97c794c62e/oviewer/oviewer.go#L365

Sometimes it would be preferable to keep the screen contents on exit. Other tools like Less offer this via option `-X` or environment variable `LESS=X`:

https://serverfault.com/questions/785949

### PR DESCRIPTION
**Pull request by aranjan7**
… where we write document from start till pager quits to original terminal

### CODE REVIEW

**Comment by noborus** [comment]
Thank you for the pull request.

However, if I add it, I would do the following.
```
func (root *Root) WriteOriginalTillQuit() {
	root.writeOriginal(0)
}

func (root *Root) WriteOriginal() {
	root.writeOriginal(root.Doc.topLN)
}

func (root *Root) writeOriginal(ln int) {
	m := root.Doc
	p := 0
	for n := ln; ; n++ {
```

However, I still don't know I need to output that many lines.
If anything, I think it might be better to be able to specify fewer lines.

**Comment by aranjan7** [comment]
Sure I can redo the patch, but first allow me to convince you for the need.

I am using this in standalone cli terminal app. If you are familiar with Cisco cli, there pagers behavior is similar to what I am proposing with above fix. In a typical session, users prints a table and scroll for a page or two, and then exit the pager when they see the rows which are interest. Then after sometime you go up the terminal and paste relevant outputs from multiple commands in a bug etc. People are used to such workflow in this world.

I understand that if I am on bash and looking at documents through pager, I actually don't want to pollute my primary terminal. In that case I agree with you that fewer (or 0) lines should be dumped.

On a side note I believe we should also have a mode where "alternate terminal" is not invoked at all. That could be larger fix, which at the moment I cannot take up. This is because currently by terminal blinks whenever I exit and call writeOriginal.

So if I am not able to convince you above, alternatively, would you consider making Doc.topLN field public. At least this way I don't have to maintain a fork.

**Comment by noborus** [comment]
Thank you for telling me the reason.
I agree that you may want to output more lines that don't fit on the screen.
If it is not essential to output from the first line, I think it is better to limit the output (1000, 10000 lines, etc.).If it is a small file, it will be output from the beginning.
If so, I think I can add ov to specify the number of lines in the CLI options and settings.

> If I am not able to convince you above, alternatively, would you consider making Doc.topLN field public. At least this way I don't have to maintain a fork.

I will be able to get Doc.topLN eventually (add a function).

**Comment by aranjan7** [comment]
Thanks for promptly getting back. I am not sure I understand what's the next step for me. Looks like you are leaning towards doing a separate fix yourself to facilitate something similar to the function I proposed. I am fine with that.

Meanwhile should I submit a pull request for a public 'get' function to get topLN? Will wait for your guidance.

**Comment by noborus** [comment]
Thank you for your contribution.
I would be grateful if you could leave the implementation to me.
I make a pull request, so if you have any problems please comment.

**Comment by aranjan7** [comment]
Ok sounds good. Thank you.

**Comment by noborus** [comment]
I've merged #147, so I'll close it.
Thank you very much.

**Pull request closed without merging**
