### PR TITLE
receiver cleanup

### PR DESCRIPTION
**Pull request by ccoVeille**
- **Refactor to use consistent parserState receiver**
- **Clean unused receivers**

### CODE REVIEW

**Comment by noborus** [comment]
Thank you for the pull request.
By the way, was this pointed out in some lint check?

**Comment by noborus** [comment]
Thank you for the pull request.
This should also erase the associated tests.

**Comment by ccoVeille** [comment]
> Thank you for the pull request.
> By the way, was this pointed out in some lint check?

Yes, exactly.

This one is a part of revive

https://revive.run/r#unused-receiver

> Description: This rule warns on unused method receivers. Methods with unused receivers can be a symptom of an unfinished refactoring or a bug.

**Comment by ccoVeille** [comment]
I'm an huge advocate of code liniting.

I opened some PR about fixing the "obvious" issues. Then I was planing to suggest adding automatic golangci-lint CI action to the repository

**Comment by ccoVeille** [comment]
By "suggesting", I mean helping you 😁

**Review by noborus — APPROVED** [review]
I agree with stricter lint checks, so I'll merge it.

**Pull request merged**
