### PR TITLE
CI: Generate release tarballs with vendored modules

### PR DESCRIPTION
**Pull request by CyberTailor**
For easier packaging.

### CODE REVIEW

**Comment by noborus** [comment]
Thank you for PR.

Is it okay to understand that once the goreleaser issue is resolved, I don't have to add the github action step?
https://github.com/goreleaser/goreleaser/issues/2911

**Comment by noborus** [comment]
Thank you for PR.

Is it okay to understand that once the goreleaser issue is resolved, I don't have to add the github action step?
https://github.com/goreleaser/goreleaser/issues/2911

**Comment by CyberTailor** [comment]
Thanks for the link. Looks like so.

**Comment by noborus** [comment]
Thank you for reply.

I want to decide whether to implement it with goreleaser or merge pr before the next release.

**Comment by noborus** [comment]
Merged (may change in the future).
Thank you very much.

**Pull request merged**
