### PR TITLE
Remove unused method

### PR DESCRIPTION
**Pull request by ccoVeille**
searchPositionStr is not exported and not used, it can be removed.

### CODE REVIEW

**Comment by noborus** [comment]
Thank you for the pull request.
This should also erase the associated tests.

**Comment by ccoVeille** [comment]
> Thank you for the pull request.
> This should also erase the associated tests.

I'm unsure what you meant.

This function is not yet used either in code or tests.

I didn't dig into code history, yet.

Can you explain a bit more?

Thanks

**Comment by noborus** [comment]
Old tests are here.
https://github.com/noborus/ov/blob/f883dcc2eea7f55b8f799fdc5e934e273528a512/oviewer/search_test.go#L480

**Comment by ccoVeille** [comment]
> Thank you for the pull request. This should also erase the associated tests.

I'm sorry, I should have spotted it, but I'm surprised the CI didn't.

I will check the open an issue + PR if needed

**Comment by ccoVeille** [comment]
> > Thank you for the pull request. This should also erase the associated tests.
> 
> I'm sorry, I should have spotted it, but I'm surprised the CI didn't.
> 
> I will check the open an issue + PR if needed

I created #527

**Review by noborus — APPROVED** [review]
thank you very much. i appreciate.

**Pull request merged**
